services:
  - type: web
    name: tatuzinho-api
    runtime: docker
    region: ohio
    plan: free
    envVars:
      - key: ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: LOG_LEVEL
        value: INFO
      - key: DEBUG
        value: false
