import unicodedata


PT_BR_TO_EN: dict[str, str] = {
    "brasil": "Brazil",
    "alemanha": "Germany",
    "inglaterra": "England",
    "franca": "France",
    "espanha": "Spain",
    "italia": "Italy",
    "holanda": "Netherlands",
    "paises baixos": "Netherlands",
    "portugal": "Portugal",
    "argentina": "Argentina",
    "uruguai": "Uruguay",
    "colombia": "Colombia",
    "chile": "Chile",
    "equador": "Ecuador",
    "peru": "Peru",
    "paraguai": "Paraguay",
    "bolivia": "Bolivia",
    "venezuela": "Venezuela",
    "mexico": "Mexico",
    "canada": "Canada",
    "estados unidos": "USA",
    "japao": "Japan",
    "coreia do sul": "South Korea",
    "arabia saudita": "Saudi Arabia",
    "australia": "Australia",
    "ira": "Iran",
    "marrocos": "Morocco",
    "tunisia": "Tunisia",
    "argelia": "Algeria",
    "egito": "Egypt",
    "nigeria": "Nigeria",
    "gana": "Ghana",
    "camaroes": "Cameroon",
    "senegal": "Senegal",
    "costa do marfim": "Ivory Coast",
    "africa do sul": "South Africa",
    "suecia": "Sweden",
    "dinamarca": "Denmark",
    "noruega": "Norway",
    "finlandia": "Finland",
    "polonia": "Poland",
    "suica": "Switzerland",
    "belgica": "Belgium",
    "croacia": "Croatia",
    "servia": "Serbia",
    "romenia": "Romania",
    "hungria": "Hungary",
    "turquia": "Turkey",
    "grecia": "Greece",
    "tchequia": "Czech Republic",
    "republica tcheca": "Czech Republic",
    "eslovaquia": "Slovakia",
    "eslovenia": "Slovenia",
    "ucrania": "Ukraine",
    "russia": "Russia",
    "austria": "Austria",
    "escocia": "Scotland",
    "irlanda": "Ireland",
    "pais de gales": "Wales",
    "israel": "Israel",
    "costa rica": "Costa Rica",
    "honduras": "Honduras",
    "panama": "Panama",
    "haiti": "Haiti",
    "jamaica": "Jamaica",
    "cuba": "Cuba",
    "nova zelandia": "New Zealand",
    "catar": "Qatar",
    "emirados arabes unidos": "UAE",
    "oma": "Oman",
    "bahrein": "Bahrain",
    "jordania": "Jordan",
    "iraque": "Iraq",
    "siria": "Syria",
    "libano": "Lebanon",
    "kuwait": "Kuwait",
    "china": "China",
    "coreia do norte": "North Korea",
    "india": "India",
    "indonesia": "Indonesia",
    "tailandia": "Thailand",
    "vietna": "Vietnam",
    "filipinas": "Philippines",
    "uzbequistao": "Uzbekistan",
    "cazaquistao": "Kazakhstan",
    "burkina faso": "Burkina Faso",
    "mali": "Mali",
    "zambia": "Zambia",
    "cabo verde": "Cape Verde",
    "guine": "Guinea",
    "guine-bissau": "Guinea-Bissau",
    "guine equatorial": "Equatorial Guinea",
    "serra leoa": "Sierra Leone",
    "togo": "Togo",
    "benin": "Benin",
    "rd congo": "DR Congo",
    "republica democratica do congo": "DR Congo",
    "etiopia": "Ethiopia",
    "sudao": "Sudan",
    "angola": "Angola",
    "madagascar": "Madagascar",
    "bosnia e herzegovina": "Bosnia and Herzegovina",
    "macedonia do norte": "North Macedonia",
    "albania": "Albania",
    "montenegro": "Montenegro",
    "bulgaria": "Bulgaria",
    "irlanda do norte": "Northern Ireland",
    "luxemburgo": "Luxembourg",
    "georgia": "Georgia",
    "armenia": "Armenia",
    "azerbaijao": "Azerbaijan",
    "gambia": "Gambia",
    "islandia": "Iceland",
    "mauritania": "Mauritania",
    "namibia": "Namibia",
    "tanzania": "Tanzania",
    "kosovo": "Kosovo",
    "suriname": "Suriname",
    "nova caledonia": "New Caledonia",
    "fiji": "Fiji",
    "taiti": "Tahiti",
    "libia": "Libya",
    "niger": "Niger",
    "chade": "Chad",
    "botswana": "Botswana",
    "burundi": "Burundi",
    "comores": "Comoros",
    "djibuti": "Djibouti",
    "essuatini": "Eswatini",
    "lesoto": "Lesotho",
    "liberia": "Liberia",
    "malawi": "Malawi",
    "maldivas": "Maldives",
    "mauricio": "Mauritius",
    "mianmar": "Myanmar",
    "moçambique": "Mozambique",
    "mocambique": "Mozambique",
    "quenia": "Kenya",
    "ruanda": "Rwanda",
    "seicheles": "Seychelles",
    "somalia": "Somalia",
    "sudao do sul": "South Sudan",
    "timor leste": "Timor-Leste",
    "zimbabue": "Zimbabwe",
    "camboja": "Cambodia",
    "gua": "Guam",
    "laos": "Laos",
    "macau": "Macau",
    "mongolia": "Mongolia",
    "papua nova guine": "Papua New Guinea",
    "singapura": "Singapore",
    "taiwan": "Taiwan",
    "sri lanka": "Sri Lanka",
    "butao": "Bhutan",
    "brunei": "Brunei",
    "nepal": "Nepal",
    "quirguistao": "Kyrgyzstan",
    "tajiquistao": "Tajikistan",
    "turcomenistao": "Turkmenistan",
    "palestina": "Palestine",
    "iemen": "Yemen",
    "anguila": "Anguilla",
    "antigua e barbuda": "Antigua and Barbuda",
    "aruba": "Aruba",
    "barbados": "Barbados",
    "belize": "Belize",
    "bermudas": "Bermuda",
    "ilhas virgens britanicas": "British Virgin Islands",
    "ilhas caimao": "Cayman Islands",
    "curacao": "Curaçao",
    "dominica": "Dominica",
    "republica dominicana": "Dominican Republic",
    "el salvador": "El Salvador",
    "granada": "Grenada",
    "guadalupe": "Guadeloupe",
    "guiana": "Guyana",
    "guiana francesa": "French Guiana",
    "ilhas virgens americanas": "US Virgin Islands",
    "montserrat": "Montserrat",
    "nicaragua": "Nicaragua",
    "porto rico": "Puerto Rico",
    "sao cristovao e nevis": "Saint Kitts and Nevis",
    "santa lucia": "Saint Lucia",
    "sao martinho": "Saint Martin",
    "sao vicente e granadinas": "Saint Vincent and the Grenadines",
    "sint maarten": "Sint Maarten",
    "ilhas turcas e caicos": "Turks and Caicos Islands",
    "samoa americana": "American Samoa",
    "ilhas cook": "Cook Islands",
    "samoa": "Samoa",
    "ilhas salomao": "Solomon Islands",
    "tonga": "Tonga",
    "vanuatu": "Vanuatu",
    "ilhas marshall": "Marshall Islands",
}


def strip_accents(s: str) -> str:
    return (
        unicodedata.normalize("NFKD", s)
        .encode("ascii", "ignore")
        .decode("ascii")
        .strip()
        .lower()
    )


EN_TO_PT_BR: dict[str, str] = {}
for pt_br, en in PT_BR_TO_EN.items():
    EN_TO_PT_BR[strip_accents(en)] = pt_br

EN_TO_PT_BR.update({
    "cape verde islands": "cabo verde",
    "congo dr": "rd congo",
    "cote d'ivoire": "costa do marfim",
    "united states": "estados unidos",
})


def normalize_team_name(name: str) -> str:
    return PT_BR_TO_EN.get(strip_accents(name), name)
